### ISSUE TITLE
master javascript pre-work exercises giving 'whoops' error when running 'test'

### ISSUE THREAD

**Issue by christianmartinroffey** [4GeeksAcademy/master-javascript-programming-exercises#117]
when trying to test the code to verify if it's correct, the is a "whoops" error :

"Woops! There has been an internal error". See screenshot attached for more info:

![Captura de pantalla 2022-05-09 a las 17 30 39](https://user-images.githubusercontent.com/81240124/167444763-e486d7df-82d0-48e5-b74e-2ed116deaa46.png)

**Comment by christianmartinroffey** [comment]
begins at exercise 8

**Comment by tommygonzaleza** [comment]
Hello! We already fix this problem, thanks for reporting it
