### ISSUE TITLE
Excersice #032 - The statement is a bit confusing. Like the message of the test when it fails.

### ISSUE THREAD

**Issue by AbreuY** [4GeeksAcademy/master-javascript-programming-exercises#80]
The statement says:

> Write a function called addObjectProperty.
> Given two objects and a key, addObjectProperty sets a new property on the 1st object at the given key. The value of that new property is the entire 2nd object.

```
var person1 = {
  name: 'Joe Blow',
  role: 'schlub'
};
var person2 = {
  name: 'Mr. Burns',
  role: 'supervisor'
};
addObjectProperty(person1, 'manager', person2);
console.log(person1.manager); // --> { name: 'Mr.Burns', role: 'supervisor' }
```

This is my code:

```
var person1 = {
  name: 'Joe Blow',
  role: 'schlub'
};
var person2 = {
  name: 'Mr. Burns',
  role: 'supervisor'
};
```

```
function addObjectProperty(obj1, key, obj2) {
  // tu codigo aqui
   obj1[key] = obj2;
   return obj1[key];
}
addObjectProperty(person1, 'manager', person2);
```

This code returns this value:
```
{
  name: "Mr. Burns",
  role: "supervisor"
}
```
Nevertheless, the test fails. Returning this text:

>      ✓ (done) 0. Function addObjectProperty must exist
>      x (fail) 1. The function must return the 2nd array values with the new key 
>      x (fail) 2. The function must return the 2nd array values with the new key

This happens because the test evaluates the full value of the first object and not just the property as the statement and example code suggests.

## Proposed solution:

Change the message of the statement and example code to:

> Write a function called addObjectProperty.
> Given two objects and a key, addObjectProperty sets a new property on the 1st object at the given key. The value of that new property is the entire 2nd object. The function must return the value of the first object including the the new property added.

```
var person1 = {
  name: 'Joe Blow',
  role: 'schlub'
};
var person2 = {
  name: 'Mr. Burns',
  role: 'supervisor'
};
addObjectProperty(person1, 'manager', person2);
console.log(person1); // --> { name: 'Joe Blow', role: 'schlub', manager: { name: 'Mr. Burns', role: 'supervisor' }}
```
and change the fail test message to something like this:
"The function must return the value of the 1st object including the new property added."

**Comment by tommygonzaleza** [comment]
Issue solved, the test had an issue that two of the tests had the same name. I modified them
