### ISSUE TITLE
Exercise #033 - Logical reasoning problem. The test should evaluate false in all cases.

### ISSUE THREAD

**Issue by AbreuY** [4GeeksAcademy/master-javascript-programming-exercises#81]
This is a logical reasoning problem. Since it is illegal to drink and drive at the same time in the United States. So the test should evaluate to false in all cases.

**Comment by tommygonzaleza** [comment]
Issue solved here: https://github.com/4GeeksAcademy/master-javascript-programming-exercises/commit/4c13373a4b5c2e0886042f00fdf99d770fbb5a5a
